Add PHP to ResX generation
ppy/osu-localisation-analyser pull request #20
Opened 2021-06-05 14:42 UTC by smoogipoo

New command: `dotnet localisation from-php {osu-web}/resources/lang`

The little tokeniser I wrote doesn't support the full range of PHP syntax, for example non-string keys/values, but it passes all localisation files currently in osu!web.

Notes:
1. Nested localisations are namespaced via `.` (e.g. `beatmapsets.resx`: `panel.download.direct`).
2. It doesn't change keys other than the namespacing above. Some keys contain `-` and others contain `_` - both of these remain unchanged like the rest.
3. It replaces `:text` with string format args (e.g. from `beatmaps.resx`, `Deleted by :editor :delete_time.` becomes `Deleted by {0} {1}.`.

This is quite initial, there's surely ways in which it can be improved, like maybe the namespacing isn't what we want and it just puts resx files side-by-side with the php ones. This can all be changed in a matter of minutes (everything inside `Program.cs`) - the PHP tokenisation won't have to change.

2021-06-05 14:52 UTC, smoogipoo commented
Hang on, comment handling isn't quite working out how I want it to in tests.

2021-06-05 14:57 UTC, smoogipoo commented
Good to go

2021-06-07 07:28 UTC, smoogipoo commented
As discussed, I missed adding .cs file generation. Along with that, it really doesn't make sense to add localisations side-by-side so I'm creating the directory structure and placing files inside the C# project itself.

The tool now works by the following process:
1. Get all `lang/{lang}/{subdir}/{file}.php` files.
2. For `lang == en`, generate the .cs file as `osu.Game/Localisation/Web/{file}Strings.cs`
    1. Set the prefix to `osu.Game.Localisation.Web.{file}`.
    2. For localisation keys equal to `_`, set the name as `Default` for that particle.
    3. Pascalise all localisation keys for method members, following our syntax rules.
3. For `lang != en`, generate the .resx file as `osu.Game/Localisation/Web/file.{lang}.resx`.

A few things to note:
1. ResX also seems to be case-insensitive so some osu-web localisations may not work as expected:  
![image](https://user-images.githubusercontent.com/1329837/120975770-926f4480-c7ac-11eb-87a1-562a07f2fe0c.png)
2. There's a few inspection issues that are quite hard to mitigate. I've managed them as best as I could via heuristics in order to not mangle naming (at the cost of not following our syntax rules), but I'd say it's best to just disable inspections for this subdir or rename the keys web-side:  
![image](https://user-images.githubusercontent.com/1329837/120976390-4375df00-c7ad-11eb-88c5-cb935bc864b5.png)

2021-06-08 07:21 UTC, peppy commented
Seems to work pretty good!

One case which should be fixed is empty per-language translations (where the english default should be used, rather than an empty string):

![20210608 162048 (JetBrains Rider-EAP)](https://user-images.githubusercontent.com/191335/121141149-9dda7280-c875-11eb-9afc-45afd94eb7fd.png)

These should be omitted if not english.

2021-06-08 07:22 UTC, peppy requested changes
As mentioned.

2021-06-08 07:26 UTC, peppy commented
Just omission is fine.

2021-06-08 07:43 UTC, peppy approved these changes

2021-06-08 08:02 UTC, merged